#!/bin/bash
pkill -f "start_sim.sh"
pkill -f "start_map.sh"
pkill -f "start_rviz.sh"
pkill -f "start_localization.sh"
pkill -f "start_battery.sh"
pkill -f "start_nav2.sh"
pkill -f "start_anomaly_detector.sh"
pkill -f "start_dashboard.sh"
pkill -f "web_dashboard.py"
pkill -f "start_dynamic_obstacles.sh"
pkill -f "dynamic_obstacles.py"
pkill -f "start_waypoints.sh"
pkill -f "waypoint_navigator.py"
pkill -f "gzserver"
pkill -f "gzclient"
pkill -f "rviz2"
pkill -f "nav2"
pkill -f "amcl"
pkill -f "map_server"
echo "All terminals killed."
